apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pmm-client
  labels:
    app: pmm-client
spec:
  selector:
    matchLabels:
      name: pmm-client
  nodeSelector:
    percona-pmm: client
  template:
    metadata:
      labels:
        name: pmm-client
        percona-pmm: client
    spec:
      containers:
        - name: pmm-client
          image: percona/pmm-client:2
          command: ["/bin/sh"]
          args: ["-c", "tail -f /dev/null"]  # Keep the container running
          env:
            - name: PMM_AGENT_SERVER_ADDRESS
              value: "monitoring-service.pmm-server.svc.cluster.local:443"
            - name: PMM_AGENT_SERVER_USERNAME
              value: "admin"
            - name: PMM_AGENT_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pmm-secret
                  key: PMM_ADMIN_PASSWORD
            - name: PMM_AGENT_SERVER_INSECURE_TLS
              value: "1"
            - name: PMM_AGENT_SETUP
              value: "1"
            - name: PMM_AGENT_CONFIG_FILE
              value: "config/pmm-agent.yaml"
          volumeMounts:
            - name: pmm-client-data
              mountPath: /srv        