apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres-operator
  namespace: stackgres
spec:
  project: default
  source:
    chart: stackgres-charts/stackgres-operator
    repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
    targetRevision: 1.5.0
    helm:
      releaseName: stackgres-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stackgres
