apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnilogic-exporter
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: omnilogic-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: omnilogic-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: omnilogic-exporter
    spec:
      containers:
      - args: 
        - --omnilogic.username=${OMNILOGIC_USERNAME}
        - --omnilogic.password=${OMNILOGIC_PASSWORD}
        command:
        - /bin/omnilogic_exporter
        env:
        - name: OMNILOGIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: omnilogic-exporter
        - name: OMNILOGIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: omnilogic-exporter
        image: bjlawson/omnilogic-exporter:0.1
        imagePullPolicy: IfNotPresent
        name: omnilogic-exporter
        ports:
        - containerPort: 9190
          name: omnilogic
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: omnilogic
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tolerations:
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 300
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 300
