apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  namespace: stackgres
  name: pgbench-test
spec:
  postgres:
    version: '14.8'
  instances: 3
  sgInstanceProfile: 'size-medium'
  pods:
    persistentVolume:
      size: '10Gi'
  configurations:
    sgPostgresConfig: 'pgconfig14'
    sgPoolingConfig: 'poolconfig1'
    # backups:
    # - sgObjectStorage: 'backupconfig1'
    #   cronSchedule: '*/5 * * * *'
    #   retention: 6
  managedSql:
    scripts:
    - sgScript: cluster-scripts
  distributedLogs:
    sgDistributedLogs: 'distributedlogs'
  prometheusAutobind: true
