apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  namespace: stackgres
  name: poolconfig1
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        pool_mode: transaction
        max_client_conn: '500'
        default_pool_size: '50'
