---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-node-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-node-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-node-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: label-nodes
spec:
  selector:
    matchLabels:
      app: label-nodes
  template:
    metadata:
      labels:
        app: label-nodes
    spec:
      tolerations:
      - operator: Exists
      nodeSelector:
        node.longhorn.io/create-default-disk: 'config'
      containers:
      - name: label-nodes
        image: busybox
        command: ["sh", "-c", "kubectl label nodes $HOSTNAME node.longhorn.io/create-default-disk=config --overwrite=true"]
